"""Pydantic models for LLM responses."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field
from typing_extensions import TypedDict

# =============================================================================
# TypedDict Models (for State)
# =============================================================================


class TestCase(TypedDict):
    """Test case with coverage status."""

    id: str
    description: str
    present: bool


class FalsePositive(TypedDict):
    """False positive test case detected."""

    scenario_name: str
    scenario_path: str
    test_case_id: str
    test_case_description: str
    reason: str


class ScenarioResult(TypedDict):
    """Analysis result for a scenario."""

    scenario_name: str
    scenario_path: str
    test_cases: list[Any]  # Pydantic models from structured output


# =============================================================================
# Pydantic Models (for LLM structured output)
# =============================================================================


class GeneratedTestCase(BaseModel):
    """Test case generated by LLM."""

    id: str = Field(description="Unique identifier (e.g., TC-001)")
    description: str = Field(description="Test case description")


class TestCaseList(BaseModel):
    """List of generated test cases."""

    test_cases: list[GeneratedTestCase]


class CoverageTestCase(BaseModel):
    """Test case with coverage analysis."""

    id: str = Field(description="Test case ID")
    description: str = Field(description="Test case description")
    present: bool = Field(
        description="True if scenario contains actual test implementation for this case"
    )
    evidence: str = Field(
        default="",
        description="XML element or section that provides evidence of coverage",
    )


class CoverageAnalysis(BaseModel):
    """Coverage analysis result."""

    test_cases: list[CoverageTestCase]


class FalsePositiveCheck(BaseModel):
    """Verification result for a test case."""

    is_false_positive: bool = Field(
        description="True if scenario lacks actual verification despite claiming coverage"
    )
    reason: str = Field(description="Detailed explanation with XML evidence")
    missing_elements: list[str] = Field(
        default_factory=list,
        description="List of missing verification elements",
    )
